---
- block:
  - name: check if there are missing updates - {{category_info.name}}
    win_updates:
      category_names:
      - '{{category_info.name}}'
      state: searched
    register: pri_update_count
    become: yes
    when: category_info.finished == False

  rescue:
  - name: restart the WSUS service after a failed check
    win_service:
      name: wuauserv
      state: restarted

  - name: reboot the server after a failed check
    win_reboot:
      reboot_timeout: 1200

  - name: check if there are missing updates - {{category_info.name}} ATTEMPT 2
    win_updates:
      category_names:
      - '{{category_info.name}}'
      state: searched
    register: pri_update_count
    become: yes

- name: set no more update flag for {{category_info.name}} if not more updates and it isn't the 1st 2 iterations
  set_fact:
    update_stat: '{{update_stat|update_merge(category_info.name, True)}}'
  when: pri_update_count.found_update_count is defined and pri_update_count.found_update_count == 0 and (loop_number != 1 and loop_number != 2)

- name: install windows updates - {{category_info.name}}
  win_updates:
    category_names:
    - '{{category_info.name}}'
    state: installed
    reboot: yes
  ignore_errors: yes # get intermittent errors with this, usually 2nd round succeeds so let's ignore it
  become: yes
  register: pri_update_result
  when: pri_update_count.found_update_count is defined and pri_update_count.found_update_count > 0

- name: reboot to handle intermittent update failure
  win_reboot:
  when: pri_update_result is failed
