---
- name: determine if host supports DISM with reset base
  win_shell: |
    $version = [Environment]::OSVersion.Version
    $major = $version.Major
    $minor = $version.Minor
    if ($major -eq 6) {
        if ($minor -gt 2) {
            "true"
        } else {
            "false"
        }
    } elseif ($major -gt 6) {
        "true"
    } else {
        "false"
    }
  register: pri_cleanup_winsxs_dism_supported

# Server 2016 fails on the first few runs, retry up to 5 times
- name: run DISM with reset base on hosts that support it
  win_command: DISM.exe /Online /Cleanup-Image /StartComponentCleanup /ResetBase
  register: pri_cleanup_winsxs_cleanup_result
  until: pri_cleanup_winsxs_cleanup_result.rc == 0
  retries: 5
  delay: 1
  ignore_errors: yes
  when: pri_cleanup_winsxs_dism_supported.stdout_lines[0] == "true"

- name: run DISM to clear service packs when not Server 2008
  win_command: DISM.exe /Online /Cleanup-Image /SPSuperseded
  when: man_host_type != "2008-x86" and man_host_type != "2008-x64"

- name: run compcln to clear service packs for Server 2008
  win_command: compcln.exe /quiet
  register: pri_cleanup_winsxs_compcln_result
  when: man_host_type == "2008-x86" or man_host_type == "2008-x64"
  failed_when: pri_cleanup_winsxs_compcln_result.rc != 0 and pri_cleanup_winsxs_compcln_result.rc != -2147467259 # 0 is good the other is already run

- name: check if cleanmgr.exe is natively available
  win_stat:
    path: C:\Windows\System32\cleanmgr.exe
  register: pri_cleanup_winsxs_cleanmgr_available

- name: setup and run cleanmgr if DISM reset base wasn't supported or cleanmgr is available
  include_tasks: cleanmgr.yml
  when: pri_cleanup_winsxs_dism_supported.stdout_lines[0] == "false" or pri_cleanup_winsxs_cleanmgr_available.stat.exists == True
